klu0926/twitter-api-2023

- config/strategies/local.js
- controllers/admin-controller.js
- controllers/user-controller.js
- middleware/role-check.js
- migrations/20190115071421-create-user.js
- routes/index.js
- seeders/20230606061719-user-seeder.js
- seeders/20230606074720-add-tweets-seeders.js
- seeders/20230606083101-add-replies-seeders.js
- seeders/20230606084457-add-likes-seeders.js
- seeders/20230606084513-add-followship-seeders.js
依照之前的Code Review 對於登入做修改：
- 對於checkRole 裡面的四個東西修改成短一點的版本
- 驗證的匙後不會 include tweet 資料
- 刪除不必要的 delete
依照即時討論增加修改
- user migration role 設定成 allowNull:false
- seeders query 使用者的方式改成 "SELECT id FROM Users WHERE role <> 'admin'"
有重新用 postman 驗證一次
在麻煩看一下感謝～
> refactor: role-check, and local auth

- controllers/user-controller.js
- routes/index.js
建立註冊功能
- 檢查帳號是否兩次都相同(前端因該也會檢查，這之後可以拿掉)
- 檢查是account 跟 email 是否已經有註冊過了，並回與對應的message
- 建立使用者後會回傳成功訊息
使用postman 測試註冊，註冊成功後也測試過登入
在麻煩了，謝謝！
> feat: signup

- middleware/role-check.js
- package.json
- fix role-check with user role = 'user'
- add some npm script to make testing easier
> fix: change role check, and add some npm scripts

- controllers/user-controller.js
- seeders/20230606074720-add-tweets-seeders.js
- seeders/20230606083101-add-replies-seeders.js
- seeders/20230606084457-add-likes-seeders.js
- seeders/20230606084513-add-followship-seeders.js
新增 **GET/api/users/:id/tweets**  和  **GET/api/users/:id/replied_tweets** 兩條routes
已在postman新增Request，目前有發現replies object內會多一個userId的attributes，原因待釐清
tweets和replies都有依照最新createdAt時間排序，可先post 一筆新的tweets測試
> Get user tweets & replies

- controllers/tweet-controller.js
- controllers/user-controller.js
- routes/modules/tweets.js
- 新增加 postReply 跟 getReplies
- postReply 增加回覆到一個推文上
- getReplies 得到一個推文中的全部回覆，每則回覆帶上回覆的人，並使用 order: [['createdAt', 'DESC']]
> feat: add getReplies and postReply

- controllers/user-controller.js
新增功能：查看使用者喜歡過的推文
依照DoD規範撰寫 : 該使用者 like 過的推文清單，排序依 like 紀錄成立的時間，愈新的在愈前面
在Likes 設搜尋條件 UserId & isLike = true，並使用createdAt的時間由新到舊來排序
> Get user likes

- controllers/user-controller.js
- models/followship.js
成功回傳 get user followers 和 get user followings的資料，已在postman測試成功
根據test spec 條件：res.body[0].followingId = 2 / res.body[0].followerId = 1
因此在followship model加上與user model的關聯，透過Followership.findAll來查詢、關聯資料
應該還要再補上 **目前登入的使用者是否已追蹤這些使用者** 的attributes
其他像是 likes 的資料也需要去判斷，這個可以討論一下看要不要寫在help中可以重複使用，待補功能，先加入to-do中記錄起來
> Get user followship

- app.js
- config/config.json
- models/index.js
- setup heroku
- 目前還沒有 migrate / seed cloud db
- 可以用 https://tranquil-basin-75437.herokuapp.com/ 看到首頁
- 詳細連結在notion heroku裡面
> Heroku setup

- app.js
- config/config.json
- middleware/role-check.js
- models/index.js
測試檔中是 const helpers = require('../../_helpers');
AC文件有提到，所以直接require helpers再去使用他的getUser屬性，目前就能通過測試了
> 在 Twitter 專案裡請用 helpers.getUser(req) 來取代 req.user，以及用 helpers.ensureAuthenticated(req) 取代 req.isAuthenticated()
> fix: _helpers.js and test pass

- controllers/tweet-controller.js
- routes/modules/tweets.js
Like 使用 TweetId 跟 UserId 查詢
postLike 功能
- Like 已經存在並且isLike = true 會跳出提示
- Like 不存在 就建立一個新的同時 isLike = true
- Like 存在同時 isLike = false 就把 isLike = true
postUnlike 功能 把已經存在的like.isLike = false
- Like 不存在就跳出提示
- Like 存在同時 = false 跳出提示
- Like 存在同時 = true 就把 isLike = false
> feat: like & unlike

- controllers/followship-controller.js
- routes/index.js
- routes/modules/followship.js
＊修改deleteFollowship 使用 followingId
postFollowship:
使用者可以追隨另一個使用者
不能追隨自己，也不能追隨管理者
要追隨的使用者必須存在
已經在追隨的話會有提示
不能沒有req.body.id
deleteFollowship:
使用者可以取消追隨另一個使用者
> Followships

- controllers/user-controller.js
- middleware/role-check.js
> fix user api response message

- controllers/admin-controller.js
- controllers/user-controller.js
- middleware/error-handler.js
> User api test

- middleware/error-handler.js
> fix:error-handler

- migrations/20190115071421-create-user.js
- migrations/20230606020527-add-account-cover-to-user.js
- seeders/20230606061719-user-seeder.js
- 新增avatar & cover 的 default值
- 修改seeder中avatar & cover的值
> Fix models

- config/strategies/jwt.js
- controllers/admin-controller.js
- controllers/user-controller.js
修改user-controller中的topFollower，前10的追蹤者不包含目前登入者本身
可先撈第一次，查看follow數最高的使用者是誰，再換登入這名使用者是否還在第一個項目來確認
admin getUsers中的receivedLikesCount，修改後目前一樣會無法測試通過，一樣先comment out
> Fix admin api

- controllers/tweet-controller.js
- 在getTweets & getTweet 新增 isCurrentUserLiked 屬性
- 修改後travis & local test all pass
> fix:add isCurrentUserLiked to getTweets and getTweet

- config/strategies/local.js
- controllers/user-controller.js
> Fix login message

- migrations/20230606020527-add-account-cover-to-user.js
- 更新cover預設為AC指定山景照
- 須重跑migrate
> fix: change the default cover

- controllers/user-controller.js
add additional check to make sure file is no undefined
> fix putUserProfile check file?.avatar?

- app.js
allow cors to run all domain while developing
> fix: change cors to allow all access

- controllers/admin-controller.js
- package.json
- routes/modules/admin.js
add a GET /admin/tweets so admin can get all the tweets
> feat: add admin get tweets

- controllers/user-controller.js
- package.json
- fix npm test script so travis can run 
- fix isCurrentUserFollowed 邏輯
> Fix is current user follower2

- controllers/admin-controller.js
- controllers/user-controller.js
- routes/modules/admin.js
新增admin usersdata route
把 account 已註冊 修改成帳號已註冊
> Fix admin users

- README.md
- migrations/20190115071421-create-user.js
renew readme and fix cover image url
> Fix readme

- controllers/user-controller.js
> feat: getUserData add tweet count

- controllers/user-controller.js
- seeders/20230606061719-user-seeder.js
- fix top follower exclude root
- setting can not change account to other 
- seed user avatar fix to 10 different image
> Fix setting

- controllers/tweet-controller.js
> Fix replies

- controllers/user-controller.js
- 修改 GET user/:id/likes (getUserLikes) 裡面的 isCurrentUserLike 邏輯，之前只會比對 :id 跟 token 使用者是否是同一個人，目前會依照每個 tweet 去比對。
- local spec - success
- 修改 GET user/:id/replied_tweets (getUserReplies) 在裡面增加 tweet.user 的資訊
- local spec - success
> Fix get user like

- seeders/20230606061719-user-seeder.js
更新user seeder
種子資料從預設10個帳號修改成15個(含root)
> fix:amount of user seeder

- config/strategies/local.js
- controllers/user-controller.js
- middleware/role-check.js
- fix error message base on AC user story
> Fix message

- package-lock.json
- socket/helper/index.js
- socket/index.js
- socket/modules/join.js
- socket/modules/leave.js
- socket/modules/sendMessage.js
- socket/modules/userOnline.js
- 使用者上線event
- 使用者下線event
- 使用者聊天event
- socket/helper
> Socket event

- socket/modules/join.js
- socket/modules/leave.js
add error message in join and leave event
- when client using join while is already on the userOnline list
- when client using leave while is already NOT on the userOnline list
> feat: add error message in join and leave

- app.js
> fix: socket cores

- socket/helper/index.js
- socket/index.js
- socket/modules/disconnect.js
- socket/modules/join.js
- socket/modules/leave.js
- add disconnected event to detect when client disconnected
- disconnected function will take out the user that disconnected ( it does a server-leave automatically)
> add detect disconnected 

- config/config.json
> fix: change heroku set up

- config/config.json
- socket/helper/index.js
- socket/modules/disconnect.js
- socket/modules/join.js
- add a setTimeout to disconnect
- 使用者要是斷線會觸發 5 秒的 setTimout，時間到才會實際移除使用者並觸發 server-leave
- 使用者使用 client-join 時會用 account 來確認使用者是 reconnect 還是新上線
- 要是使用者是 reconnect (表示還在上線名單上) 就會取消 setTimout
> Fix disconnect

- package-lock.json
- socket/index.js
- socket/modules/record.js
1. 觸發client-record事件時，會回傳一包records
2. 暫時先把room放入function參數中，之後如要做一對一聊天室，公開聊天室需要給一個數值ID才不會影響sequelize搜尋條件
3. postman測試過有收到回傳的records array
> Chat record

- socket/index.js
- socket/modules/getRoom.js
- socket/modules/sendMessage.js
change client-message property
> refactor: client-get-room property

- socket/index.js
- socket/modules/newMessage.js
- socket/modules/sendMessage.js
1. 新增newMessage.js，取得私訊聊天室中，每一個聊天室的最新一筆chats
2. 當sendMessage觸發時，執行後會觸發newMessage.js，更新最新聊天室訊息
3. 目前用postman測試會出現小bug，當sendMessage傳送的roomId不在原本user socket.rooms裡的話，newMessage會沒辦法回傳新創的聊天室訊息 => 待修
> New message

- migrations/20230711132326-create-read.js
- models/read.js
- socket/helper/index.js
- socket/index.js
- socket/modules/disconnect.js
- socket/modules/enterRoom.js
- socket/modules/getRoom.js
- socket/modules/join.js
- socket/modules/leave.js
- socket/modules/newMessage.js
- socket/modules/sendMessage.js
Create
- create Read table
- create enterRoom(roomId) function, use client-enter-room event
--- enterRoom require user to client-join first
--- enterRoom will update user's Read record about a room
--- user can only enterRoom he/she belongs to, else use client-get-room first
--- if user was in a different room, it will auto update last room's Read record
Change
- change the helper.findUserInPublic(input, typeString) => (input, typeString, checkExist = true)
- checkExist property when true will throw error if can't find user, default to true
- change other files that use findUserInPublic to fit the original purpose
> Read table

- socket/index.js
- socket/modules/getRoom.js
- socket/modules/newMessage.js
- socket/modules/sendMessage.js
發現觸發client-get-room之後，currentUser裡的rooms不會馬上更新
已解決在新聊天室發送訊息後，newMessage.js回傳的message不會包含新創聊天室的最新訊息bug
> fix: newMessage bug

- socket/modules/newMessage.js
> feat: unread messages

- socket/modules/newMessage.js
> fix: remove message id

- socket/helper/index.js
- socket/index.js
- socket/modules/enterRoom.js
- socket/modules/join.js
- socket/modules/leave.js
- socket/modules/leaveRoom.js
- socket/modules/read.js
- socket/modules/sendMessage.js
新增
client-enter-room (roomId) : 建立一個參數 user.currentRoom = roomId 
client-leave-room (roomId) : 刪除一個參數 delete user.currentRoom
enter 跟 leave 都會觸發一次 read
修改
client-message 會去抓目前 currentRoom 裡面的使用者，並且每個人都觸發一次 read
發現問題：
目前 client-new-message 會觸發到不相關的使用者，例如使用者 沒有 room 3, 可是當 room 3 有新訊息時他也會收到 server-new-message
> Enter leave room

- socket/index.js
- socket/modules/disconnect.js
- socket/modules/enterRoom.js
- socket/modules/leave.js
- socket/modules/leaveRoom.js
增加
- client-leave 或是斷線都會自動觸發 client-leave-room (間接觸發 read)
- client-leave-room 不需要參數
修改
- disconnect 裡面的 setTimeout 直接拿 leave 來使用
> Fix leave room

- socket/modules/newMessage.js
- socket/modules/sendMessage.js
> fix: new message

- socket/modules/sendMessage.js
fix sendMessage to save chat to db before run client-new-message
> fix: sendMessage create Chat record before trigger new-message

- models/room.js
- socket/modules/newMessage.js
更新：
server-new-message回傳的資料，新增targetUser屬性，可以抓目前使用者每個聊天室的對象資料
> feat: add newMessage attribute:targetUser

- controllers/user-controller.js
- seeders/20230720054920-add-notice-seeder.js
- socket/helper/index.js
- socket/modules/getNotice.js
- socket/modules/pushNotice.js
新增: getNotice.js
只取得未讀的通知，如果全部都已經讀過則不會顯示任何資料，當以下條件發生時，會獲得最新通知：
1. 訂閱的對象發布新的推文
2. 有人reply登入者的推文
3. 有人like登入者的推文
4. 有人follow登入者
修改:
1. notice seeder中的 newNotice, noticeRead value值設為new Date()，才不會出問題
** 須重跑seeders
詳細回傳資料可看[文件](https://www.notion.so/socket-5384cf0e187341ecb8ae907cf6993293?pvs=4#c104c7c994f946d98b9fad27f562273b)
> Get notice

- socket/helper/index.js
- socket/modules/getNotice.js
更新
get notice目前會抓固定天數內新增的事件，因為Seed重跑會跑出一堆通知，所以日期先暫設1天
若要調整天數，修改這行後方的number即可
const sevenDaysAgo = calculateDate(currentDate, 1)
> refactor: revise notification's date

- socket/index.js
- socket/modules/newMessage.js
- socket/modules/read.js
- socket/modules/sendMessage.js
更新：
client-message 不需要使用 roomId, 而是使用 currentRoom, 要是沒有 currentRoom 就是公開頻道
Bug修改：
修復了使用者在聊天室傳遞訊息會顯示 unreadMessage = 1 的問題，原因是因為沒有使用 Promise.all 包住 read，造成的時間順序問題。
> fix: send message use Promise all to read and send newMessageEvent

- socket/modules/enterRoom.js
- socket/modules/getNotice.js
- socket/modules/leave.js
- socket/modules/leaveRoom.js
修改幾處因該要使用await 的部分
修改 getNotice 會拿取 7天內的資料
> Await fixes

- socket/helper/index.js
- socket/modules/getNotice.js
修改getNotice
使用者不會拿到訂閱前對象發的Tweet通知
> fix: user won't get tweets notice before subscribe

- app.js
- socket/helper/index.js
- socket/index.js
- socket/modules/disconnect.js
- socket/modules/enterRoom.js
- socket/modules/join.js
- socket/modules/leave.js
- socket/modules/leaveRoom.js
- socket/modules/sendMessage.js
- socket/modules/updateRoom.js
更新：
- 公開頻道也需要使用 client-enter-room('public')
新增：
- server-update-room 會更新目前只用者房間內的使用者名單回傳 訊息 string + users array
> Server update room

- models/subscribe.js
- socket/helper/index.js
- socket/index.js
- socket/modules/getNotice.js
- socket/modules/pushNotice.js
**更新項目：**
- 於getNotice中更新，當使用者被訂閱時也會獲得通知
**修改bug：**
- 當使用者在notice頁面時，有新的通知事件觸發時，不會即時更新notice頁面
發現原本是在pushNotice中判斷是否有在notice這個房間時，加入getNotice(socket)，這個只會更新"觸發事件方"的notice，接收通知的對象實際上並未更新
> Fix notice

- socket/modules/pushNotice.js
1. 補上await，避免回傳promise物件
2. 在pushNoitce最後加入server-update，更新user data
> fix: add await and server-update

- socket/modules/pushNotice.js
先將targetId 轉string，避免後續產生資料型態不同的問題
> fix: avoid input different data type error

- socket/modules/pushNotice.js
> test: add words to find bug
